### ISSUE TITLE
provide a more convenient way to set `load-path` option 

### ISSUE THREAD

**Issue by kasperpeulen** [google/dart-scissors#21]
I'm trying to port the material2 repo to dart.

I saw that they do some magic so that you more easily can import scss files in your component stylesheet. See this line;
https://github.com/angular/material2/blob/master/src/components/button/button.scss#L1

So basically they resolve imports not relative to the component itself, but relative to the `src/core/style` directory.

Now I was also able to do this with scissors as well:

```
transformers:
- scissors:
    sasscArgs:
    - '--load-path'
    - '/Users/kasper/Code/DartProjects/material2/lib/core/style'
```

But I would like to do it for example like this:

```
transformers:
- scissors:
    sasscArgs:
    - '--load-path'
    - 'lib/core/style'
```

Or maybe there could be some convention? For how to import `scss` files?

**Comment by ochafik** [comment]
Hey @kasperpeulen, sorry for the delay!

Definitely seems like some bespoke handling of include paths would be useful, thanks for the suggestion!

Would you have a branch with an example use case so I can toy with it?

**Comment by ochafik** [comment]
Quick update: Scissors should now fully support `-I` and `--load-path` args in `sasscArgs` (even with relative paths, and/or with environment variables such as `${PWD}`).

The example you quoted should work out of the box:
```
transformers:
- scissors:
    sasscArgs:
    - --load-path
    - lib/core/style
    - -Ilib/somewhere/else
```

Please let me know if you find any issue, will try and cut a release pretty soon.
