### ISSUE TITLE
Allow custom overrides of bidirectionalized CSS

### ISSUE THREAD

**Issue by ochafik** [google/dart-scissors#22]
See issue #4: we need to support any existing `[dir=rtl]` selectors to allow for a smooth transition for code that is already doing manual bidirectionalization (suggestion from @blackhc).

**Comment by ochafik** [comment]
Added support for CSSJanus's `/* @noflip */` comments in 7e8e114ad157b6ea37431a3e89e6d46169dce41b, which should allow for some overrides.

**Comment by MonamAgarwal** [comment]
Css mirroring has support for custom overrides. Different rules for ltr and rtl languages can be easily added. For example: 
/* @noflip */
:host-context([dir="ltr"]) .header{
    margin-left: 5em;
}

/* @noflip */
:host-context([dir="rtl"]) .header {
    margin-right: 15em;
}
Css mirroring will have no effect on these rules.
