### ISSUE TITLE
Dart 2 runtime failures in tests

### ISSUE THREAD

**Issue by keertip** [google/dart-scissors#78]
When running tests in Dart 2 mode, see failures like

Failed to load "/scissors/test/checker/transformer_test.dart":
type '_ImmutableMap<String, dynamic>' is not a subtype of type 'Map<String, String>' of 'other' where
  _ImmutableMap is from dart:core
  String is from dart:core
  Map is from dart:core
  String is from dart:core
  String is from dart:core
dart:collection                                                                        __InternalLinkedHashMap&_HashVMBase&MapMixin.addAll
package:scissors/src/utils/settings_base.dart 61:12                                    new SettingsBase
../../scissors/lib/src/checker/settings.dart             new CheckerSettings
package:scissors/src/checker/transformer.dart 50:25                                    new CheckerTransformer.asPlugin
../..//scissors/test/checker/transformer_test.dart 9:13   makePhases

type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast where
  _InternalLinkedHashMap is from dart:collection
  Map is from dart:core
  String is from dart:core
dart:core                                                                                  Object._as
package:scissors/src/utils/settings_base.dart 60:42                                        new SettingsBase
../scissors/lib/src/css_pruning/settings.dart             new __CssPruningSettings&SettingsBase&CssPruningSettings
../../tmp/archives/third_party/dart/scissors/lib/src/css_pruning/settings.dart             new _CssPruningSettings
package:scissors/src/css_pruning/transformer.dart 35:18                                    new CssPruningTransformer.asPlugin
../../scissors/test/css_pruning/transformer_test.dart 23:13  makePhases

and more ....

**Comment by keertip** [comment]
/cc @srawlins 

@ochafik

**Comment by srawlins** [comment]
These are tricky to reproduce, but I think I have some solid steps:

1. Expand the range of the args constraint in pubspec to something like `">=0.12.0 <0.14.0"`
2. Change the analyzer constraint in pubspec to `^0.31.2-alpha` (or something similar, not sure)
3. `pub upgrade`. This should give us deps that have fixed their runtime issues.
4. Run these tests:
   * `dart --preview-dart-2 test/css_pruning/transformer_test.dart`
   * `dart --preview-dart-2 test/permutations/transformer_test.dart`
   * `dart --preview-dart-2 test/reloader/transformer_test.dart`
   * `dart --preview-dart-2 test/sass/transformer_test.dart`
